plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.5.1'
    id 'checkstyle'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    String jUnitVersion = '5.14.4'

    testImplementation "org.junit.jupiter:junit-jupiter-api:${jUnitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${jUnitVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
}

javafx {
    version = '21.0.6'
    modules = [ 'javafx.controls' ]
}

application {
    mainClass = 'nelson.Launcher'
}

shadowJar {
    archiveFileName = 'nelson-all.jar'

    manifest {
        attributes 'Main-Class': 'nelson.Launcher'
    }
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}

test {
    useJUnitPlatform()
}

run {
    standardInput = System.in
}
